#define _pdr_define_const_file \
	/* 文件共享 */\
	REGISTER_LONG_CONSTANT("FILE_SHARE_DELETE", FILE_SHARE_DELETE, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_SHARE_READ", FILE_SHARE_READ, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_SHARE_WRITE", FILE_SHARE_WRITE, CONST_CS|CONST_PERSISTENT);\
\
	/* 文件打开 */\
	REGISTER_LONG_CONSTANT("CREATE_ALWAYS", CREATE_ALWAYS, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("CREATE_NEW", CREATE_NEW, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("OPEN_ALWAYS", OPEN_ALWAYS, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("OPEN_EXISTING", OPEN_EXISTING, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("TRUNCATE_EXISTING", TRUNCATE_EXISTING, CONST_CS|CONST_PERSISTENT);\
\
	/* 文件属性 */\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_ARCHIVE", FILE_ATTRIBUTE_ARCHIVE, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_ENCRYPTED", FILE_ATTRIBUTE_ENCRYPTED, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_HIDDEN", FILE_ATTRIBUTE_HIDDEN, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_NORMAL", FILE_ATTRIBUTE_NORMAL, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_NOT_CONTENT_INDEXED", FILE_ATTRIBUTE_NOT_CONTENT_INDEXED, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_NORMAL", FILE_ATTRIBUTE_NORMAL, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_HIDDEN", FILE_ATTRIBUTE_HIDDEN, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_ENCRYPTED", FILE_ATTRIBUTE_ENCRYPTED, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_ATTRIBUTE_ARCHIVE", FILE_ATTRIBUTE_ARCHIVE, CONST_CS|CONST_PERSISTENT);\
\
	/* 文件标记 */\
	REGISTER_LONG_CONSTANT("FILE_FLAG_BACKUP_SEMANTICS", FILE_FLAG_BACKUP_SEMANTICS, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_DELETE_ON_CLOSE", FILE_FLAG_DELETE_ON_CLOSE, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_NO_BUFFERING", FILE_FLAG_NO_BUFFERING, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_OPEN_NO_RECALL", FILE_FLAG_OPEN_NO_RECALL, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_OPEN_REPARSE_POINT", FILE_FLAG_OPEN_REPARSE_POINT, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_POSIX_SEMANTICS", FILE_FLAG_POSIX_SEMANTICS, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_RANDOM_ACCESS", FILE_FLAG_RANDOM_ACCESS, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_SEQUENTIAL_SCAN", FILE_FLAG_SEQUENTIAL_SCAN, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("FILE_FLAG_WRITE_THROUGH", FILE_FLAG_WRITE_THROUGH, CONST_CS|CONST_PERSISTENT);\
\
	/* 文件安全 */\
	REGISTER_LONG_CONSTANT("SECURITY_ANONYMOUS", SECURITY_ANONYMOUS, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("SECURITY_CONTEXT_TRACKING", SECURITY_CONTEXT_TRACKING, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("SECURITY_DELEGATION", SECURITY_DELEGATION, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("SECURITY_EFFECTIVE_ONLY", SECURITY_EFFECTIVE_ONLY, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("SECURITY_IDENTIFICATION", SECURITY_IDENTIFICATION, CONST_CS|CONST_PERSISTENT);\
	REGISTER_LONG_CONSTANT("SECURITY_IMPERSONATION", SECURITY_IMPERSONATION, CONST_CS|CONST_PERSISTENT);\

