#define	_pdr_define_const_window_msg \
\
	/* windowœ˚œ¢ */\
	REGISTER_LONG_CONSTANT("WM_USER", WM_USER, CONST_CS|CONST_PERSISTENT) ;\
	REGISTER_LONG_CONSTANT("WM_COMMAND", WM_COMMAND, CONST_CS|CONST_PERSISTENT) ;
